class TestError(Exception): pass

class NotFoundError(TestError): pass